version: '2'

services:
  # template for front-1, front-2, front-3
  frontend:
    image: sva/frontend
    ports:
      - "2551"
      - "8080"
    links:
      - backend
    environment:
      - seed.hostname=backend
      - actor.ask.timeout.ms=60000
      - JAVA_OPTS=-Xmx256m -Xss256k
      # needed for haproxy
      - EXCLUDE_PORTS=2551

  backend:
    image: sva/backend
    ports:
      - "2550"
    environment:
      - clustering.hostname=backend
      - actor.ask.timeout.ms=60000

  lb:
    image: dockercloud/haproxy
    ports:
      - "80:80"
    links:
      - frontend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
