version: '2'

services:
  frontend:
    image: sva/frontend
    ports:
      - "2551"
      - "8080"
    links:
      - backend
    environment:
      - spring.profiles.include=docker
      - seed.hostname=backend
      - actor.ask.timeout.ms=60000
      # - JAVA_OPTS=-Xmx256m -Xss256k
      # needed for haproxy
      - EXCLUDE_PORTS=2551

  backend:
    image: sva/backend
    ports:
      - "2550"
    environment:
      - spring.profiles.include=docker
      - clustering.hostname=backend
      - actor.ask.timeout.ms=60000

  lb:
    image: dockercloud/haproxy
    ports:
      - "80:80"
    links:
      - frontend
    volumes:
      # to retrieve information about other docker images
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
     - OPTION=httpchk get /check
