version: '2'

services:
  frontend:
    image: sva/frontend
    links:
      - backend
    ports:
      - "2551:2551"
      - "8080:8080"
    environment:
      - seed.hostname=backend
      - clustering.hostname=frontend
      - JAVA_OPTS=-Xmx256m -Xss256k

  backend:
    image: sva/backend
    ports:
      - "2550:2550"
    environment:
      - clustering.hostname=backend

